name: Deploy to development environment

# Controls when the action will run
on:
  # Triggers the workflow on push events only for the main branch
  push:
    branches:
      - main
      - master

  # Allows to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-app:
    name: Deploy to dev
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Yarn install and Cache dependencies
        uses: graasp/graasp-deploy/.github/actions/yarn-install-and-cache@v1

      - name: Yarn build
        # Set environment variables required to perform the build. These are only available to this step
        env:
          REACT_APP_GRAASP_APP_ID: ${{ secrets.APP_ID }}
          REACT_APP_VERSION: ${{ github.sha }}
        run: yarn build
        shell: bash

      - name: Deploy
        uses: graasp/graasp-deploy/.github/actions/deploy-s3-app@v1
        # Replace input build-folder or version if needed
        with:
          build-folder: 'build'
          graasp-app-id: ${{ secrets.APP_ID }}
          version: 'latest'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ vars.APPS_AWS_REGION_DEV }}
          aws-s3-bucket-name: ${{ vars.AWS_S3_BUCKET_NAME_APPS_DEV }}
          cloudfront-distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_APPS_DEV }}
